import type { AppState, User } from "./types";

function ago(minutes: number) {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

const rahul: User = {
  id: "rahul",
  name: "Rahul Kumar",
  phone: "+91 98000 00021",
  email: "rahul@localmate.app",
  role: "helper",
  language: "hi",
  city: "Rishikesh",
  area: "laxman",
  rating: 4.9,
  tasksCompleted: 83,
  responseRate: 96,
  memberSince: "2026",
  identityVerified: true,
  phoneVerified: true,
  conductAccepted: true,
  categories: ["luggage", "transport", "scooter", "shopping", "guide"],
  bioEn: "I know Tapovan, the jhulas, and the ghats. Luggage, scooters, and local errands.",
  bioHi: "तपोवन, झूला और घाट अच्छे से पता हैं। सामान, स्कूटर, और लोकल काम।",
  reviews: [
    { id: "r1", by: "Elena", stars: 5, text: "Very helpful and arrived on time." },
    { id: "r2", by: "Jonah", stars: 5, text: "Handled two heavy bags without any fuss." },
    { id: "r3", by: "Maya", stars: 5, text: "Clear Hindi and English. Easy to coordinate." },
  ],
};

const amit: User = {
  id: "amit",
  name: "Amit Singh",
  phone: "+91 98000 00034",
  email: "amit@localmate.app",
  role: "helper",
  language: "hi",
  city: "Rishikesh",
  area: "highbank",
  rating: 4.6,
  tasksCompleted: 41,
  responseRate: 91,
  memberSince: "2026",
  identityVerified: true,
  phoneVerified: true,
  conductAccepted: true,
  categories: ["scooter", "repair", "transport"],
  bioEn: "Scooter runs and small repairs around High Bank and Tapovan.",
  bioHi: "हाई बैंक और तपोवन के आसपास स्कूटर और छोटी मरम्मत।",
  reviews: [{ id: "a1", by: "Jonah", stars: 5, text: "Got my scooter to the mechanic the same afternoon." }],
};

const sameer: User = {
  id: "sameer",
  name: "Sameer Ali",
  phone: "+91 98000 00048",
  email: "sameer@localmate.app",
  role: "helper",
  language: "hi",
  city: "Rishikesh",
  area: "ram",
  rating: 4.7,
  tasksCompleted: 29,
  responseRate: 88,
  memberSince: "2026",
  identityVerified: false,
  phoneVerified: true,
  conductAccepted: false,
  categories: [],
  bioEn: "Translation help for clinics, cafes, and guesthouses.",
  bioHi: "क्लिनिक, कैफ़े और गेस्टहाउस के लिए अनुवाद।",
  reviews: [{ id: "s1", by: "Elena", stars: 5, text: "Patient translator. I understood every step at the clinic." }],
};

const priya: User = {
  id: "priya",
  name: "Priya Nautiyal",
  phone: "+91 98000 00052",
  email: "priya@localmate.app",
  role: "helper",
  language: "hi",
  city: "Rishikesh",
  area: "triveni",
  rating: 4.8,
  tasksCompleted: 56,
  responseRate: 97,
  memberSince: "2026",
  identityVerified: true,
  phoneVerified: true,
  conductAccepted: true,
  categories: ["shopping", "photo", "cleaning", "delivery"],
  bioEn: "Market runs, guesthouse errands, and quiet photo walks.",
  bioHi: "मार्केट, गेस्टहाउस के काम, और शांत फोटो वॉक।",
  reviews: [{ id: "p1", by: "Maya", stars: 5, text: "Knew the best light near Ram Jhula. Easy morning." }],
};

export function seedState(): AppState {
  return {
    sessionUserId: null,
    users: [
      {
        id: "maya",
        name: "Maya Ellis",
        phone: "+91 98000 11110",
        email: "maya@localmate.app",
        role: "customer",
        language: "en",
        city: "Rishikesh",
        area: "tapovan",
        rating: 5,
        tasksCompleted: 1,
        responseRate: 100,
        memberSince: "2026",
        identityVerified: false,
        phoneVerified: true,
        bioEn: "Staying in Tapovan for a few weeks.",
        bioHi: "कुछ हफ्ते तपोवन में हूँ।",
        reviews: [{ id: "m1", by: "Priya", stars: 5, text: "Clear instructions and ready on time." }],
      },
      rahul,
      amit,
      sameer,
      priya,
      {
        id: "elena",
        name: "Elena Berg",
        phone: "+91 98000 22220",
        email: "elena@localmate.app",
        role: "customer",
        language: "en",
        city: "Rishikesh",
        area: "tapovan",
        rating: 5,
        tasksCompleted: 2,
        responseRate: 100,
        memberSince: "2026",
        identityVerified: true,
        phoneVerified: true,
        bioEn: "Visiting from Oslo.",
        bioHi: "ओस्लो से आई हूँ।",
        reviews: [],
      },
      {
        id: "jonah",
        name: "Jonah Mehta",
        phone: "+91 98000 33330",
        email: "jonah@localmate.app",
        role: "customer",
        language: "en",
        city: "Rishikesh",
        area: "highbank",
        rating: 4.9,
        tasksCompleted: 1,
        responseRate: 100,
        memberSince: "2026",
        identityVerified: false,
        phoneVerified: true,
        bioEn: "Weekend in Rishikesh.",
        bioHi: "ऋषिकेश में वीकेंड।",
        reviews: [],
      },
    ],
    tasks: [
      {
        id: "task-luggage",
        customerId: "elena",
        category: "luggage",
        title: "Need someone to pick up my luggage",
        titleHi: "किसी को मेरा सामान उठाना है",
        details: "2 bags, need help taking them to my hostel",
        detailsHi: "2 बैग हैं, इन्हें मेरे हॉस्टल तक ले जाने में मदद चाहिए",
        area: "tapovan",
        toArea: "laxman",
        whenId: "today-5",
        whenLabel: "Today, 5 PM",
        whenLabelHi: "आज, शाम 5 बजे",
        priceMode: "fixed",
        budget: 500,
        status: "looking",
        locationShared: false,
        createdAt: ago(35),
      },
      {
        id: "task-scooter",
        customerId: "jonah",
        category: "scooter",
        title: "Need help taking scooter to mechanic",
        titleHi: "स्कूटर को मैकेनिक तक ले जाने में मदद चाहिए",
        details: "It will not start. Mechanic is near Laxman Jhula.",
        detailsHi: "स्टार्ट नहीं हो रहा। मैकेनिक लक्ष्मण झूला के पास है।",
        area: "highbank",
        toArea: "laxman",
        whenId: "today-eve",
        whenLabel: "Today, evening",
        whenLabelHi: "आज, शाम",
        priceMode: "negotiable",
        budget: 300,
        status: "looking",
        locationShared: false,
        createdAt: ago(80),
      },
      {
        id: "task-translate",
        customerId: "elena",
        category: "translation",
        title: "Need Hindi to English help for 1 hour",
        titleHi: "1 घंटे के लिए हिंदी से अंग्रेज़ी मदद चाहिए",
        details: "Clinic visit. I need someone who can translate clearly.",
        detailsHi: "क्लिनिक जाना है। किसी ऐसे व्यक्ति की ज़रूरत है जो साफ़ अनुवाद कर सके।",
        area: "ram",
        whenId: "tomorrow-10",
        whenLabel: "Tomorrow, 10 AM",
        whenLabelHi: "कल, सुबह 10 बजे",
        priceMode: "fixed",
        budget: 600,
        status: "looking",
        locationShared: false,
        createdAt: ago(140),
      },
      {
        id: "task-shop",
        customerId: "jonah",
        category: "shopping",
        title: "Grocery run at the local market",
        titleHi: "लोकल मार्केट से राशन लाना है",
        details: "Rice, fruit, and drinking water for the guesthouse.",
        detailsHi: "गेस्टहाउस के लिए चावल, फल, और पीने का पानी।",
        area: "triveni",
        whenId: "today-5",
        whenLabel: "Today, 5 PM",
        whenLabelHi: "आज, शाम 5 बजे",
        priceMode: "negotiable",
        budget: 400,
        status: "looking",
        locationShared: false,
        createdAt: ago(200),
      },
      {
        id: "task-photo",
        customerId: "maya",
        category: "photo",
        title: "Sunrise photos near Ram Jhula",
        titleHi: "राम झूला के पास सूर्योदय की फोटो",
        details: "One hour, nothing posed. Just the river and the bridge.",
        detailsHi: "एक घंटा, पोज़ नहीं। बस नदी और पुल।",
        area: "ram",
        whenId: "tomorrow-10",
        whenLabel: "Tomorrow, 10 AM",
        whenLabelHi: "कल, सुबह 10 बजे",
        priceMode: "fixed",
        budget: 700,
        status: "completed",
        helperId: "priya",
        agreedAmount: 700,
        locationShared: false,
        createdAt: ago(60 * 24 * 3),
      },
    ],
    offers: [
      {
        id: "offer-amit-scooter",
        taskId: "task-scooter",
        helperId: "amit",
        amount: 280,
        note: "I can do this",
        createdAt: ago(50),
      },
      {
        id: "offer-priya-shop",
        taskId: "task-shop",
        helperId: "priya",
        amount: 400,
        note: "I can do this",
        createdAt: ago(90),
      },
    ],
    messages: [
      {
        id: "msg-photo",
        taskId: "task-photo",
        senderId: "system",
        text: "You are connected. Keep the task and payment inside LocalMate.",
        createdAt: ago(60 * 24 * 3),
      },
    ],
    notifications: [],
    reports: [],
    blocks: [],
    payments: [],
  };
}
